/**
 * processUpload — S3 trigger (s3:ObjectCreated on events/ prefix)
 *
 * Responsibilities (Phase 1):
 *  1. Parse eventId + mediaId from the S3 key
 *  2. Skip thumbnail derivatives (thumbs/ directory)
 *  3. Validate file magic bytes (first 12 bytes)
 *  4. Update MEDIA record status → 'visible'
 *
 * TODO (Phase 2 — requires sharp Lambda layer):
 *  - Generate 300px thumbnail → events/{eventId}/thumbs/{mediaId}.jpg
 *  - Generate 800px medium  → events/{eventId}/thumbs/{mediaId}_md.jpg
 *  - Write thumbnailKey + mediumKey + width + height back to MEDIA record
 *
 * TODO (Phase 3 — Premium only):
 *  - Run Rekognition DetectModerationLabels
 *  - If NSFW score > threshold → set status='pending_review' + notify host
 */

import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3';

import { getItem, updateItem, queryItems } from '../../shared/dynamodb.mjs';
import { logger } from '../../shared/logger.mjs';

const s3 = new S3Client({});

// ── Magic byte signatures ──────────────────────────────────────────────────────
// Each entry: { mime, check: (buf) => boolean }
const MAGIC_CHECKS = [
  // JPEG: FF D8 FF
  { mime: 'image/jpeg', check: (b) => b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff },
  // PNG: 89 50 4E 47 0D 0A 1A 0A
  { mime: 'image/png', check: (b) => b[0] === 0x89 && b[1] === 0x50 && b[2] === 0x4e && b[3] === 0x47 },
  // WebP: 52 49 46 46 ?? ?? ?? ?? 57 45 42 50
  { mime: 'image/webp', check: (b) => b[0] === 0x52 && b[1] === 0x49 && b[2] === 0x46 && b[3] === 0x46 && b[8] === 0x57 && b[9] === 0x45 && b[10] === 0x42 && b[11] === 0x50 },
  // HEIC/HEIF: ftyp box at byte 4 (bytes 4-7 = 66 74 79 70)
  { mime: 'image/heic', check: (b) => b[4] === 0x66 && b[5] === 0x74 && b[6] === 0x79 && b[7] === 0x70 },
  { mime: 'image/heif', check: (b) => b[4] === 0x66 && b[5] === 0x74 && b[6] === 0x79 && b[7] === 0x70 },
  // MP4 / MOV: ftyp at byte 4 (same as HEIC pattern but different brand bytes)
  { mime: 'video/mp4', check: (b) => b[4] === 0x66 && b[5] === 0x74 && b[6] === 0x79 && b[7] === 0x70 },
  { mime: 'video/quicktime', check: (b) => b[4] === 0x66 && b[5] === 0x74 && b[6] === 0x79 && b[7] === 0x70 },
  // WebM / Matroska: 1A 45 DF A3
  { mime: 'video/webm', check: (b) => b[0] === 0x1a && b[1] === 0x45 && b[2] === 0xdf && b[3] === 0xa3 },
  // MP3: ID3 tag (49 44 33) or sync word (FF FB/FA/F3/F2)
  { mime: 'audio/mpeg', check: (b) => (b[0] === 0x49 && b[1] === 0x44 && b[2] === 0x33) || (b[0] === 0xff && (b[1] & 0xe0) === 0xe0) },
  // WAV: RIFF...WAVE
  { mime: 'audio/wav', check: (b) => b[0] === 0x52 && b[1] === 0x49 && b[2] === 0x46 && b[3] === 0x46 },
  // M4A / audio/mp4: same ftyp container as MP4
  { mime: 'audio/mp4', check: (b) => b[4] === 0x66 && b[5] === 0x74 && b[6] === 0x79 && b[7] === 0x70 },
  // WebM audio
  { mime: 'audio/webm', check: (b) => b[0] === 0x1a && b[1] === 0x45 && b[2] === 0xdf && b[3] === 0xa3 },
];

/**
 * Fetch the first N bytes of an S3 object using Range header.
 */
async function fetchMagicBytes(bucket, key, byteCount = 12) {
  const cmd = new GetObjectCommand({
    Bucket: bucket,
    Key: key,
    Range: `bytes=0-${byteCount - 1}`,
  });
  const response = await s3.send(cmd);

  const chunks = [];
  for await (const chunk of response.Body) {
    chunks.push(chunk);
  }
  return Buffer.concat(chunks);
}

/**
 * Detect MIME type from magic bytes.
 * Returns detected mime string or null if unknown.
 */
function detectMimeFromBuffer(buf) {
  for (const { mime, check } of MAGIC_CHECKS) {
    try {
      if (check(buf)) return mime;
    } catch {
      // Buffer too short — skip
    }
  }
  return null;
}

/**
 * Parse eventId and mediaId from an S3 key.
 *
 * Expected format: events/{eventId}/{mediaId}.{ext}
 * Returns null if the key does not match the expected pattern.
 */
function parseS3Key(key) {
  // Skip thumbnail derivatives — they are generated by processUpload itself
  if (key.includes('/thumbs/')) return null;

  const match = key.match(/^events\/(evt_[^/]+)\/([^/]+)$/);
  if (!match) return null;

  const eventId = match[1];
  const filename = match[2];                     // e.g. med_abc123.jpg
  const mediaId = filename.replace(/\.[^.]+$/, ''); // strip extension

  if (!mediaId.startsWith('med_')) return null;

  return { eventId, mediaId };
}

/**
 * Find the MEDIA DynamoDB record for a given mediaId.
 * We query by PK=EVENT#{eventId} with SK prefix MEDIA# and then filter by mediaId
 * because the exact SK timestamp is embedded in the record itself.
 */
async function findMediaRecord(eventId, mediaId) {
  // The SK pattern is MEDIA#{uploadedAt}#{mediaId}
  // We need to scan with a filter since we don't know the exact timestamp.
  const result = await queryItems(
    `EVENT#${eventId}`,
    'MEDIA#',
    {
      filterExpr: 'mediaId = :mediaId',
      exprValues: { ':mediaId': mediaId },
      limit: 1,
    },
  );
  return result.items[0] ?? null;
}

export async function handler(event) {
  // S3 events can have multiple records (though usually one)
  const results = await Promise.allSettled(
    event.Records.map((record) => processRecord(record)),
  );

  // Log any failures but do not throw — S3 will not retry on success
  for (const result of results) {
    if (result.status === 'rejected') {
      logger.error('processUpload record failed', { error: result.reason?.message });
    }
  }
}

async function processRecord(record) {
  const bucket = record.s3.bucket.name;
  const key = decodeURIComponent(record.s3.object.key.replace(/\+/g, ' '));

  logger.info('Processing S3 object', { bucket, key });

  // ── Skip thumbs directory ──────────────────────────────────────────────
  if (key.includes('/thumbs/')) {
    logger.debug('Skipping thumbnail key', { key });
    return;
  }

  // ── Parse eventId + mediaId ────────────────────────────────────────────
  const parsed = parseS3Key(key);
  if (!parsed) {
    logger.warn('S3 key does not match expected pattern — skipping', { key });
    return;
  }

  const { eventId, mediaId } = parsed;

  // ── Validate magic bytes ───────────────────────────────────────────────
  let magicBuf;
  try {
    magicBuf = await fetchMagicBytes(bucket, key, 12);
  } catch (err) {
    logger.error('Failed to fetch magic bytes', { key, error: err.message });
    // Mark as failed so it is not surfaced to guests
    await safeSetStatus(eventId, mediaId, 'hidden', 'magic_byte_fetch_failed');
    return;
  }

  const detectedMime = detectMimeFromBuffer(magicBuf);
  if (!detectedMime) {
    logger.warn('File failed magic byte validation — marking hidden', { key, mediaId });
    await safeSetStatus(eventId, mediaId, 'hidden', 'invalid_file_type');
    return;
  }

  logger.debug('Magic bytes validated', { mediaId, detectedMime });

  // ── Load MEDIA record ──────────────────────────────────────────────────
  const mediaRecord = await findMediaRecord(eventId, mediaId);
  if (!mediaRecord) {
    logger.warn('MEDIA record not found for processed object', { eventId, mediaId });
    return;
  }

  // ── Cross-check declared MIME vs detected MIME ─────────────────────────
  // For image/video/audio: we verify at the category level to handle HEIC/MP4 ambiguity.
  const declaredCategory = (mediaRecord.fileType || '').split('/')[0];
  const detectedCategory = detectedMime.split('/')[0];

  if (declaredCategory !== detectedCategory) {
    logger.warn('MIME category mismatch', {
      mediaId,
      declared: mediaRecord.fileType,
      detected: detectedMime,
    });
    await safeSetStatus(eventId, mediaId, 'hidden', 'mime_mismatch');
    return;
  }

  // ── Update MEDIA record → 'visible' ───────────────────────────────────
  const sk = mediaRecord.SK;

  await updateItem(
    `EVENT#${eventId}`,
    sk,
    'SET #status = :visible, detectedMime = :mime',
    { ':visible': 'visible', ':mime': detectedMime },
    { '#status': 'status' },
    null,
  );

  logger.info('Media marked visible', { eventId, mediaId, detectedMime });

  // TODO (Phase 2 — sharp layer required):
  // 1. Download full object from S3 into a Buffer
  // 2. Use sharp to generate 300px thumbnail → upload to events/{eventId}/thumbs/{mediaId}.jpg
  // 3. Use sharp to generate 800px medium   → upload to events/{eventId}/thumbs/{mediaId}_md.jpg
  // 4. Read width/height metadata from sharp output
  // 5. Update MEDIA record: thumbnailKey, mediumKey, width, height

  // TODO (Phase 3 — Premium NSFW moderation):
  // 1. Load event record to check tier === 'premium' && autoApprove === false
  // 2. Call rekognition.DetectModerationLabels({ Image: { S3Object: { Bucket, Name: key } }, MinConfidence: 70 })
  // 3. If labels found with Confidence > threshold: set status='pending_review', moderationLabels=[...]
  // 4. Notify host via SES if emailNotifications === true
}

/**
 * Best-effort status update — logs on failure rather than throwing.
 */
async function safeSetStatus(eventId, mediaId, status, reason) {
  try {
    const mediaRecord = await findMediaRecord(eventId, mediaId);
    if (!mediaRecord) return;

    await updateItem(
      `EVENT#${eventId}`,
      mediaRecord.SK,
      'SET #status = :status, rejectionReason = :reason',
      { ':status': status, ':reason': reason },
      { '#status': 'status' },
      null,
    );
  } catch (err) {
    logger.error('safeSetStatus failed', { eventId, mediaId, status, error: err.message });
  }
}
